### ISSUE TITLE
Aprropriately document necessity of `tokio_unstable`

### ISSUE THREAD

**Issue by jan-ferdinand** [Neptune-Crypto/neptune-core#529]
As mentioned [here](https://github.com/Neptune-Crypto/neptune-core/issues/523#issuecomment-2750354168), when using Neptune core as a library, it is necessary to pass the build flag `tokio_unstable`:

```toml
# .cargo/config.toml
[build]
rustflags = ["--cfg", "tokio_unstable"]
```

Until #394 is resolved, this should at least be documented. Once #394 is resolved, it should be documented that this build flag is required for certain crate features.
